apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenkins-exam.fullname" . }}-cast
  labels:
    {{- include "jenkins-exam.labels" . | nindent 4 }}
    app: cast
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.cast.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: cast
    release: {{ .Release.Name }}
