apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jenkins-exam.fullname" . }}-nginx
  labels:
    {{- include "jenkins-exam.labels" . | nindent 4 }}
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: nginx
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: nginx
          image: {{ .Values.nginx.image }}
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "jenkins-exam.fullname" . }}-nginx-config
