apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenkins-exam.fullname" . }}-nginx
  labels:
    {{- include "jenkins-exam.labels" . | nindent 4 }}
    app: nginx
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: nginx
    release: {{ .Release.Name }}
