movie:
  replicaCount: 1
  image:
    repository: blayres/movie-service
    pullPolicy: IfNotPresent
    tag: "k8s-test"
  service:
    port: 8000
  database:
    host: movie-db
    port: 5432
    name: movie_db_dev
    username: movie_db_username
    password: movie_db_password

cast:
  replicaCount: 1
  image:
    repository: blayres/cast-service
    pullPolicy: IfNotPresent
    tag: "k8s-test"
  service:
    port: 8000
  database:
    host: cast-db
    port: 5432
    name: cast_db_dev
    username: cast_db_username
    password: cast_db_password

movieDb:
  image: postgres:12.1
  port: 5432

castDb:
  image: postgres:12.1
  port: 5432

nginx:
  image: nginx:latest
  service:
    type: NodePort
    port: 8080
